version: '3.7'


services:


  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=(&lz2p9h!_+c_la_-^i#yd4_7+p0xch!#u!5m7jxg&$_f76l6%
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db


  db: 
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    


volumes:
  postgres_data: